language: node_js
node_js: stable

install:
  - yarn install

script:
  - yarn build

after_script:
  - cd dist
  - git init
  - git config user.name "sinchang"
  - git config user.email "sinchangwen@gmail.com"
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

branches:
  only:
    - master

env:
  global:
    - GH_REF: github.com/sinchang/vstar.git
    - secure: feI1KtnK8zvt9B4nYgjYVkMcUsPhNQG3zvDoq+ILm0u2BDocmkcWCfL6kJUSbHOftU3CMg7UsJCPFhd2CTwM6JigNgMxmqjYQAgszffAjqcctxiRSUIL4rm3b8u+T6/sx9nVHcka2hytIzyFZ4X2xI8gbm2tRAhBdrc57kGAtSeCIBBZ6Fy45sKUZ0h8sTFjN9dVv6r2nOW5UIlIY4DFc++8geMDEj18mk8RQSs9b9AW3N9uD47V8HnzL4vF3j+X0+pvFhq8k6HGiJLGHIoHc9h8yf/u86y2wSYZDtPfDAZCuv4H1N/Vhj8Zk6yAFuBX0cneajE294/JZj3nOWZSQuL25jOYMWy02c66buajvCrDyHmXTMNCz5maqOIzk5uevbBUAC/NKSPwt8LELHhTuSOZFbj2OkSBL0jXZCDGjVv0idaAEVTjbcFNTmvzZHhj/q8Ja6bLHzeugPCDWWPeR5g1O5GbI31V1/zvMM6uVHyiAleQEGkXw0xB7GkQmPy5USm38Gkuk5utUEs9QlitZDgV4LtoggnC2Z83wcdNs+J2FCRQsriWa8jOFWLPVt6x2u3NmihaAARvwbcQDpiuyLGVi5n3prS/KrzkMxq1oNfzBpGzI3a94uVxKxtdk1rJc8PMogK10MtNG1ueVOOgB79Pkxd++W2RD8dpxpIrXuo=
